# Generated by Django 4.2.6 on 2023-11-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_project', models.BigIntegerField()),
                ('fk_employee', models.BigIntegerField()),
                ('role', models.TextField()),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_employee', models.BigIntegerField()),
                ('fK_position', models.BigIntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('pause', models.FloatField()),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.TextField(max_length=50)),
                ('forename', models.TextField(max_length=50)),
                ('surname', models.TextField(max_length=50)),
                ('mail', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
                ('fk_team_id', models.BigIntegerField()),
                ('team_roll', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_employee', models.BigIntegerField()),
                ('fk_position', models.BigIntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'forecast',
            },
        ),
        migrations.CreateModel(
            name='Positon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_id', models.TextField(max_length=50)),
                ('fk_project', models.BigIntegerField()),
                ('rate', models.FloatField()),
                ('wd', models.FloatField()),
                ('volume_total', models.FloatField()),
                ('volume_remaining', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.TextField(max_length=50)),
                ('name', models.TextField(max_length=50)),
                ('company', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fk_creator', models.BigIntegerField()),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
